import java.util.Scanner;
public class ArithmeticExceptionDemo {
	public static void main(String[] args) {
		int quotient,dividend,divisor;
		int flag = 0;
		Scanner scnr = new Scanner(System.in);
		try {
			System.out.println("Enter dividend");
			dividend = scnr.nextInt();
			System.out.println("Enter divisor");
			divisor = scnr.nextInt();
			quotient =dividend / divisor;
			flag = 1;
			System.out.println("Quotient = " + quotient);
		}  catch(ArithmeticException arthexcp) {// object is thrown by jvm
			while(flag == 0) {
				System.out.println("Enter divisor");
				divisor = scnr.nextInt();
			}
		}
		
	}
}
