import java.util.Scanner;
public class ArithmeticExceptionDemo{  
	
	public void toCal(int dividend, int divisor) {
		int quotient = 0;
		quotient = dividend / divisor;
	}
	
	public static void main(String[] args) {
		ArithmeticExceptionDemo exception = new ArithmeticExceptionDemo();
		Scanner scnr = new Scanner(System.in);
		System.out.println("Enter dividend");
		int dividend = scnr.nextInt();
		System.out.println("Enter divisor");
		int divisor = scnr.nextInt();
		try {
			exception.toCal(dividend, divisor);
		} catch(ArithmeticException e) {
			System.out.println("Enter divisor");
			divisor = scnr.nextInt();
			exception.toCal(dividend, divisor);
		}
	}
}